// GENERATED FILE, DO NOT EDIT.
//
// Built by tools/bundle-functions.js from index.ts plus _shared/door.ts,
// inlined into one file so it can be pasted into the Supabase dashboard,
// which cannot express an import reaching outside the function's folder.
//
// Edit index.ts or _shared/door.ts and regenerate:
//
//   node tools/bundle-functions.js
//
// Deploying with the CLI uses index.ts and ignores this file entirely.

// ── inlined from _shared/door.ts ──────────────────────────────
// Shared helpers for the three door Edge Functions.
//
// Plain fetch against PostgREST rather than a Supabase client library: the
// functions only ever call RPCs, the repo's habit is few dependencies, and
// a door should not stop working because a CDN pinned an import badly.

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

/** Calls a SECURITY DEFINER function as the service role. */
async function rpc<T>(name: string, args: Record<string, unknown> = {}): Promise<T> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: "POST",
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(args),
  });
  if (!res.ok) {
    throw new Error(`rpc ${name} failed: ${res.status} ${await res.text()}`);
  }
  return (await res.json()) as T;
}

/**
 * The caller's address.
 *
 * cf-connecting-ip is set by the edge and replaces anything the client
 * sent, so it is the one to trust. x-forwarded-for is a fallback and the
 * LAST entry is the one the platform appended; the earlier entries can be
 * anything the client felt like typing.
 */
function clientIp(req: Request): string | null {
  const cf = req.headers.get("cf-connecting-ip");
  if (cf) return cf.trim();

  const xff = req.headers.get("x-forwarded-for");
  if (xff) {
    const parts = xff.split(",").map((p) => p.trim()).filter(Boolean);
    if (parts.length) return parts[parts.length - 1];
  }
  return req.headers.get("x-real-ip")?.trim() ?? null;
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Compares without an early return, so the time taken does not depend on
 * how many leading bytes happened to line up.
 */
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

/**
 * PBKDF2-SHA256, 256 bit output. Must match tools/make-pass.js exactly, or
 * no pass generated by the CLI will ever match one stored in the database.
 *
 * Takes the salt as hex and builds the buffer here rather than accepting a
 * Uint8Array: an annotated Uint8Array widens to Uint8Array<ArrayBufferLike>
 * under strict TypeScript, which deriveBits will not accept.
 */
async function pbkdf2(
  pass: string,
  saltHex: string,
  iterations: number,
): Promise<Uint8Array> {
  const salt = new Uint8Array(saltHex.length >> 1);
  for (let i = 0; i < salt.length; i++) {
    salt[i] = parseInt(saltHex.substring(i * 2, i * 2 + 2), 16);
  }

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(pass),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt, iterations },
    key,
    256,
  );
  return new Uint8Array(bits);
}

// `supabase secrets set --env-file` on a line like `DOOR_ALLOWED_ORIGIN=`
// sets an empty string, not an unset variable, and ?? only catches null and
// undefined. That would emit `Access-Control-Allow-Origin: ""`, which no
// browser accepts, and the page would stop being able to open the door with
// nothing in the logs to explain it. Treat empty and whitespace as unset.
const ALLOWED_ORIGIN = Deno.env.get("DOOR_ALLOWED_ORIGIN")?.trim() || "*";

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers": "content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
  Vary: "Origin",
};

function json(body: unknown, status = 200, extra: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
      ...corsHeaders,
      ...extra,
    },
  });
}

/**
 * Compares a caller supplied key against the expected one without an early
 * return. Missing or misconfigured keys fail closed.
 */
function keyMatches(supplied: string | null, expected: string | undefined): boolean {
  if (!expected || !supplied) return false;
  const enc = new TextEncoder();
  return timingSafeEqual(enc.encode(supplied), enc.encode(expected));
}

// ── door-open/index.ts ──────────────────────────────────────────
// door-open: the only public endpoint.
//
//   page -> here -> queue a command row -> ESP32 picks it up
//
// The browser posts characters and gets back a verdict. It never sees a
// hash, never sees a pass id, and decides nothing. Everything below runs
// server side.
//
// Deploy:
//   supabase functions deploy door-open --no-verify-jwt
//
// --no-verify-jwt is required: this endpoint is reached by a guest with no
// Supabase account and no token. Its authentication is the pass itself.


// Queued commands die after this. A request captured off the wire cannot
// be replayed into an open a minute later, because there is nothing left
// to claim.
const COMMAND_TTL_SECONDS = 30;

// Lock out an IP after this many failures inside the window. A six or
// eight character pass with no lockout is brute forced in an afternoon.
const MAX_FAILURES_PER_IP = 5;
const LOCKOUT_WINDOW_SECONDS = 900;

// Backstop for someone rotating IPs, which defeats the per IP lockout
// entirely. Set high enough that ordinary use never reaches it.
const MAX_FAILURES_GLOBAL = 30;

// Nothing legitimate is longer than this. Without a cap, a megabyte of
// input would be run through PBKDF2 once per stored pass.
const MAX_PASS_LENGTH = 64;

type Candidate = { id: string; salt: string; hash: string; iterations: number };
type ConsumeRow = {
  outcome: string;
  command_id: number | null;
  label: string | null;
  valid_from: string | null;
  valid_until: string | null;
};

/**
 * The keypad only emits characters from the pass alphabet, but people also
 * type, and they add spaces and dashes when a pass is written down. Strip
 * to letters and digits and upper case it. make-pass.js hashes the same
 * normalised form, so the two always agree.
 */
function normalise(raw: string): string {
  return raw.toUpperCase().replace(/[^0-9A-Z]/g, "");
}

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== "POST") return json({ ok: false, reason: "error" }, 405);

  const ip = clientIp(req);

  try {
    let pass = "";
    try {
      const body = await req.json();
      pass = typeof body?.pass === "string" ? normalise(body.pass) : "";
    } catch {
      pass = "";
    }

    if (!pass || pass.length > MAX_PASS_LENGTH) {
      await rpc("door_log_attempt", { p_ip: ip, p_outcome: "unknown" });
      return json({ ok: false, reason: "unknown" });
    }

    // Lockout first, before any hashing. Being locked out is not a secret:
    // the person is told, so there is nothing to leak by answering fast.
    const locked = await rpc<boolean>("door_ip_locked", {
      p_ip: ip,
      p_max_failures: MAX_FAILURES_PER_IP,
      p_window_seconds: LOCKOUT_WINDOW_SECONDS,
    });
    if (locked) {
      await rpc("door_log_attempt", { p_ip: ip, p_outcome: "locked_out" });
      return json({ ok: false, reason: "locked_out", retry_after: LOCKOUT_WINDOW_SECONDS }, 429);
    }

    const throttled = await rpc<boolean>("door_globally_throttled", {
      p_max_failures: MAX_FAILURES_GLOBAL,
      p_window_seconds: LOCKOUT_WINDOW_SECONDS,
    });
    if (throttled) {
      await rpc("door_log_attempt", { p_ip: ip, p_outcome: "throttled" });
      return json({ ok: false, reason: "throttled", retry_after: LOCKOUT_WINDOW_SECONDS }, 429);
    }

    const candidates = await rpc<Candidate[]>("door_candidates");

    // Every stored pass is hashed and compared, with no break on match.
    // Breaking early would make a pass stored first answer faster than one
    // stored last, which over enough samples says which pass matched.
    let matchedId: string | null = null;
    for (const c of candidates) {
      const derived = await pbkdf2(pass, c.salt, c.iterations);
      if (timingSafeEqual(derived, hexToBytes(c.hash))) matchedId = c.id;
    }

    // With no passes stored at all the loop above costs nothing, and a
    // near instant answer would say so. Burn one round instead.
    if (candidates.length === 0) {
      await pbkdf2(pass, "0".repeat(32), 120000);
    }

    if (!matchedId) {
      await rpc("door_log_attempt", { p_ip: ip, p_outcome: "unknown" });
      return json({ ok: false, reason: "unknown" });
    }

    // The pass is right. Whether it is usable right now is decided in the
    // database, under a row lock, in the same transaction that increments
    // the use counter.
    const rows = await rpc<ConsumeRow[]>("door_consume", {
      p_pass_id: matchedId,
      p_ip: ip,
      p_ttl_seconds: COMMAND_TTL_SECONDS,
    });
    const result = rows[0];

    if (result?.outcome === "opened") {
      return json({ ok: true, reason: "opened", ttl: COMMAND_TTL_SECONDS });
    }

    // Past this point the caller has proved they know a real pass, so
    // telling them why it did not work gives nothing away.
    return json({
      ok: false,
      reason: result?.outcome ?? "unknown",
      valid_from: result?.valid_from ?? null,
      valid_until: result?.valid_until ?? null,
    });
  } catch (err) {
    console.error("door-open failed:", err instanceof Error ? err.message : err);
    return json({ ok: false, reason: "error" }, 500);
  }
});
