// GENERATED FILE, DO NOT EDIT.
//
// Built by tools/bundle-functions.js from index.ts plus _shared/door.ts,
// inlined into one file so it can be pasted into the Supabase dashboard,
// which cannot express an import reaching outside the function's folder.
//
// Edit index.ts or _shared/door.ts and regenerate:
//
//   node tools/bundle-functions.js
//
// Deploying with the CLI uses index.ts and ignores this file entirely.

// ── inlined from _shared/door.ts ──────────────────────────────
// Shared helpers for the three door Edge Functions.
//
// Plain fetch against PostgREST rather than a Supabase client library: the
// functions only ever call RPCs, the repo's habit is few dependencies, and
// a door should not stop working because a CDN pinned an import badly.

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

/** Calls a SECURITY DEFINER function as the service role. */
async function rpc<T>(name: string, args: Record<string, unknown> = {}): Promise<T> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: "POST",
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(args),
  });
  if (!res.ok) {
    throw new Error(`rpc ${name} failed: ${res.status} ${await res.text()}`);
  }
  return (await res.json()) as T;
}

/**
 * The caller's address.
 *
 * cf-connecting-ip is set by the edge and replaces anything the client
 * sent, so it is the one to trust. x-forwarded-for is a fallback and the
 * LAST entry is the one the platform appended; the earlier entries can be
 * anything the client felt like typing.
 */
function clientIp(req: Request): string | null {
  const cf = req.headers.get("cf-connecting-ip");
  if (cf) return cf.trim();

  const xff = req.headers.get("x-forwarded-for");
  if (xff) {
    const parts = xff.split(",").map((p) => p.trim()).filter(Boolean);
    if (parts.length) return parts[parts.length - 1];
  }
  return req.headers.get("x-real-ip")?.trim() ?? null;
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Compares without an early return, so the time taken does not depend on
 * how many leading bytes happened to line up.
 */
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

/**
 * PBKDF2-SHA256, 256 bit output. Must match tools/make-pass.js exactly, or
 * no pass generated by the CLI will ever match one stored in the database.
 *
 * Takes the salt as hex and builds the buffer here rather than accepting a
 * Uint8Array: an annotated Uint8Array widens to Uint8Array<ArrayBufferLike>
 * under strict TypeScript, which deriveBits will not accept.
 */
async function pbkdf2(
  pass: string,
  saltHex: string,
  iterations: number,
): Promise<Uint8Array> {
  const salt = new Uint8Array(saltHex.length >> 1);
  for (let i = 0; i < salt.length; i++) {
    salt[i] = parseInt(saltHex.substring(i * 2, i * 2 + 2), 16);
  }

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(pass),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt, iterations },
    key,
    256,
  );
  return new Uint8Array(bits);
}

// `supabase secrets set --env-file` on a line like `DOOR_ALLOWED_ORIGIN=`
// sets an empty string, not an unset variable, and ?? only catches null and
// undefined. That would emit `Access-Control-Allow-Origin: ""`, which no
// browser accepts, and the page would stop being able to open the door with
// nothing in the logs to explain it. Treat empty and whitespace as unset.
const ALLOWED_ORIGIN = Deno.env.get("DOOR_ALLOWED_ORIGIN")?.trim() || "*";

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers": "content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
  Vary: "Origin",
};

function json(body: unknown, status = 200, extra: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
      ...corsHeaders,
      ...extra,
    },
  });
}

/**
 * Compares a caller supplied key against the expected one without an early
 * return. Missing or misconfigured keys fail closed.
 */
function keyMatches(supplied: string | null, expected: string | undefined): boolean {
  if (!expected || !supplied) return false;
  const enc = new TextEncoder();
  return timingSafeEqual(enc.encode(supplied), enc.encode(expected));
}

// ── door-admin/index.ts ──────────────────────────────────────────
// door-admin: create, edit and delete passes from tools/manage.html.
//
// The repo managed passes with SQL alone for a long time, and everything
// still can. This exists so the page on your own machine can do the same
// edits over HTTPS rather than by handing you statements to paste.
//
// What it deliberately does not do:
//
//   * It never sees a pass. manage.html derives the salt and PBKDF2 hash in
//     the browser and sends those, so "create" takes a hash and has no idea
//     what the plaintext was. Nothing here can leak what it never receives.
//   * It never returns a hash. Listing goes through door_admin_list, which
//     reads door_pass_status, and that view has never carried salt or hash.
//   * It cannot open the door. There is no path from here to door_consume
//     or door_claim, the same way door-events has no path to either.
//
// Authenticated with DOOR_ADMIN_KEY, a third key on top of the device and
// dashboard ones, so it rotates on its own. This is the most powerful of
// the three: it can mint a working pass. Treat it like a front door key.
//
// Deploy:
//   supabase functions deploy door-admin --no-verify-jwt
//   supabase secrets set DOOR_ADMIN_KEY=...


const ADMIN_KEY = Deno.env.get("DOOR_ADMIN_KEY");

// Deliberately not DOOR_ALLOWED_ORIGIN. That one is narrowed to the Netlify
// page, and manage.html is opened from a file:// URL, which sends
// `Origin: null` and would be refused by it. CORS is not what protects this
// endpoint in any case: the key is, and a browser's origin check does
// nothing about a request that did not come from a browser.
const CORS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "content-type, x-admin-key",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

const MAX_LABEL = 60;
const ITERATIONS = 120000;

type Body = {
  action?: string;
  id?: string;
  label?: string;
  kind?: string;
  salt?: string;
  hash?: string;
  valid_from?: string | null;
  valid_until?: string | null;
  max_uses?: number | null;
  off?: boolean;
};

function fail(reason: string, status = 400): Response {
  return json({ ok: false, reason }, status, CORS);
}

/** Rejects anything that is not a plain uuid, before it reaches Postgres. */
function uuid(value: unknown): string | null {
  return typeof value === "string" &&
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)
    ? value
    : null;
}

/** null stays null: it is how "no window" and "unlimited" are expressed. */
function when(value: unknown): string | null {
  if (value === null || value === undefined || value === "") return null;
  if (typeof value !== "string") return null;
  const t = Date.parse(value);
  return Number.isNaN(t) ? null : new Date(t).toISOString();
}

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "POST") return fail("method", 405);

  if (!keyMatches(req.headers.get("x-admin-key"), ADMIN_KEY)) {
    return fail("unauthorised", 401);
  }

  let body: Body;
  try {
    body = await req.json();
  } catch {
    return fail("bad_json");
  }

  try {
    switch (body.action) {
      case "list":
        return json({ ok: true, passes: await rpc("door_admin_list") }, 200, CORS);

      case "create": {
        const label = (body.label ?? "").trim();
        if (!label) return fail("label_required");
        if (label.length > MAX_LABEL) return fail("label_too_long");
        if (body.kind !== "resident" && body.kind !== "guest") return fail("bad_kind");
        // The page derives these. Checked here anyway, because this is the
        // boundary and the page is not the only thing that can call it.
        if (typeof body.salt !== "string" || !/^[0-9a-f]{32,}$/.test(body.salt)) return fail("bad_salt");
        if (typeof body.hash !== "string" || !/^[0-9a-f]{64}$/.test(body.hash)) return fail("bad_hash");

        const id = await rpc<string>("door_admin_create", {
          p_label: label,
          p_kind: body.kind,
          p_salt: body.salt,
          p_hash: body.hash,
          p_iterations: ITERATIONS,
          p_valid_from: when(body.valid_from),
          p_valid_until: when(body.valid_until),
          p_max_uses: typeof body.max_uses === "number" && body.max_uses > 0 ? body.max_uses : null,
        });
        return json({ ok: true, id }, 200, CORS);
      }

      case "revoke": {
        const id = uuid(body.id);
        if (!id) return fail("bad_id");
        const rows = await rpc<number>("door_admin_revoke", { p_id: id, p_off: body.off !== false });
        return json({ ok: rows > 0, rows }, 200, CORS);
      }

      case "window": {
        const id = uuid(body.id);
        if (!id) return fail("bad_id");
        const rows = await rpc<number>("door_admin_window", {
          p_id: id,
          p_valid_from: when(body.valid_from),
          p_valid_until: when(body.valid_until),
        });
        return json({ ok: rows > 0, rows }, 200, CORS);
      }

      case "uses": {
        const id = uuid(body.id);
        if (!id) return fail("bad_id");
        const rows = await rpc<number>("door_admin_uses", {
          p_id: id,
          p_max_uses: typeof body.max_uses === "number" && body.max_uses > 0 ? body.max_uses : null,
        });
        return json({ ok: rows > 0, rows }, 200, CORS);
      }

      case "delete": {
        const id = uuid(body.id);
        if (!id) return fail("bad_id");
        const rows = await rpc<number>("door_admin_delete", { p_id: id });
        return json({ ok: rows > 0, rows }, 200, CORS);
      }

      default:
        return fail("unknown_action");
    }
  } catch (err) {
    // The message can carry a Postgres error, which is useful here: the
    // caller already proved they hold the admin key, and "guest passes must
    // expire" is a great deal more helpful than "error".
    const message = err instanceof Error ? err.message : String(err);
    console.error("door-admin failed:", message);
    return json({ ok: false, reason: "error", detail: message }, 500, CORS);
  }
});
