// GENERATED FILE, DO NOT EDIT.
//
// Built by tools/bundle-functions.js from index.ts plus _shared/door.ts,
// inlined into one file so it can be pasted into the Supabase dashboard,
// which cannot express an import reaching outside the function's folder.
//
// Edit index.ts or _shared/door.ts and regenerate:
//
//   node tools/bundle-functions.js
//
// Deploying with the CLI uses index.ts and ignores this file entirely.

// ── inlined from _shared/door.ts ──────────────────────────────
// Shared helpers for the three door Edge Functions.
//
// Plain fetch against PostgREST rather than a Supabase client library: the
// functions only ever call RPCs, the repo's habit is few dependencies, and
// a door should not stop working because a CDN pinned an import badly.

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

/** Calls a SECURITY DEFINER function as the service role. */
async function rpc<T>(name: string, args: Record<string, unknown> = {}): Promise<T> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: "POST",
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(args),
  });
  if (!res.ok) {
    throw new Error(`rpc ${name} failed: ${res.status} ${await res.text()}`);
  }
  return (await res.json()) as T;
}

/**
 * The caller's address.
 *
 * cf-connecting-ip is set by the edge and replaces anything the client
 * sent, so it is the one to trust. x-forwarded-for is a fallback and the
 * LAST entry is the one the platform appended; the earlier entries can be
 * anything the client felt like typing.
 */
function clientIp(req: Request): string | null {
  const cf = req.headers.get("cf-connecting-ip");
  if (cf) return cf.trim();

  const xff = req.headers.get("x-forwarded-for");
  if (xff) {
    const parts = xff.split(",").map((p) => p.trim()).filter(Boolean);
    if (parts.length) return parts[parts.length - 1];
  }
  return req.headers.get("x-real-ip")?.trim() ?? null;
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Compares without an early return, so the time taken does not depend on
 * how many leading bytes happened to line up.
 */
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

/**
 * PBKDF2-SHA256, 256 bit output. Must match tools/make-pass.js exactly, or
 * no pass generated by the CLI will ever match one stored in the database.
 *
 * Takes the salt as hex and builds the buffer here rather than accepting a
 * Uint8Array: an annotated Uint8Array widens to Uint8Array<ArrayBufferLike>
 * under strict TypeScript, which deriveBits will not accept.
 */
async function pbkdf2(
  pass: string,
  saltHex: string,
  iterations: number,
): Promise<Uint8Array> {
  const salt = new Uint8Array(saltHex.length >> 1);
  for (let i = 0; i < salt.length; i++) {
    salt[i] = parseInt(saltHex.substring(i * 2, i * 2 + 2), 16);
  }

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(pass),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt, iterations },
    key,
    256,
  );
  return new Uint8Array(bits);
}

// `supabase secrets set --env-file` on a line like `DOOR_ALLOWED_ORIGIN=`
// sets an empty string, not an unset variable, and ?? only catches null and
// undefined. That would emit `Access-Control-Allow-Origin: ""`, which no
// browser accepts, and the page would stop being able to open the door with
// nothing in the logs to explain it. Treat empty and whitespace as unset.
const ALLOWED_ORIGIN = Deno.env.get("DOOR_ALLOWED_ORIGIN")?.trim() || "*";

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
  "Access-Control-Allow-Headers": "content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
  Vary: "Origin",
};

function json(body: unknown, status = 200, extra: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
      ...corsHeaders,
      ...extra,
    },
  });
}

/**
 * Compares a caller supplied key against the expected one without an early
 * return. Missing or misconfigured keys fail closed.
 */
function keyMatches(supplied: string | null, expected: string | undefined): boolean {
  if (!expected || !supplied) return false;
  const enc = new TextEncoder();
  return timingSafeEqual(enc.encode(supplied), enc.encode(expected));
}

// ── door-events/index.ts ──────────────────────────────────────────
// door-events: read only feed for the home controller's kiosk panel.
//
// It reads. It cannot claim a command and it cannot open anything. If the
// Node server could claim commands it would race the ESP32 for every press
// and roughly half of them would vanish, so this endpoint has no path to
// door_claim at all.
//
// Authenticated with DOOR_DASHBOARD_KEY, which is a different secret from
// the device key so the two rotate independently. Losing this one leaks a
// list of times and labels, not a way in.
//
// The IP column is not in door_recent_events, so it cannot be returned
// here even by accident. The dashboard is on a living room screen.
//
// Deploy:
//   supabase functions deploy door-events --no-verify-jwt
//   supabase secrets set DOOR_DASHBOARD_KEY=...


const DASHBOARD_KEY = Deno.env.get("DOOR_DASHBOARD_KEY");
const DEFAULT_LIMIT = 10;
const MAX_LIMIT = 50;

type EventRow = { id: number; at: string; outcome: string; label: string | null };

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method !== "GET" && req.method !== "POST") return json({ events: [] }, 405);

  if (!keyMatches(req.headers.get("x-dashboard-key"), DASHBOARD_KEY)) {
    return json({ events: [] }, 401);
  }

  try {
    const url = new URL(req.url);
    const asked = parseInt(url.searchParams.get("limit") ?? "", 10);
    const limit = Number.isFinite(asked) ? Math.min(Math.max(asked, 1), MAX_LIMIT) : DEFAULT_LIMIT;

    const rows = await rpc<EventRow[]>("door_recent_events", { p_limit: limit });
    return json({ events: rows });
  } catch (err) {
    console.error("door-events failed:", err instanceof Error ? err.message : err);
    return json({ events: [] }, 500);
  }
});
